meiduo/meiduo/apps/areas/urls.py
from django.conf.urls import url
from .views import AreasViews

urlpatterns = [
    #查询省市区信息
    url(r'^areas/$',AreasViews.as_view()),
]

meiduo/meiduo/apps/carts/urls.py
from django.conf.urls import url
from .views import GoodsCartsView,CartSelectedAllView,CartSimpleView
urlpatterns = [
    #商品购物车添加/展示/修改/删除
    url(r'^carts/$',GoodsCartsView.as_view()),
    #商品全选操作
    url(r'^carts/selection/$',CartSelectedAllView.as_view()),
    #展示简单版购物车数据
    url(r'^carts/simple/$',CartSimpleView.as_view()),
]

meiduo/meiduo/apps/goods/urls.py
from django.conf.urls import url
from .views import ListView,HotGoodsView,GoodsDetailView,GoodsVisitView,GoodsCommentsView

urlpatterns = [
    #商品列表页面展示"
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)/$',ListView.as_view()),
    #热销商品展示
    url(r'^hot/(?P<category_id>\d+)/$',HotGoodsView.as_view()),
    #商品详情页面展示
    url(r'^detail/(?P<sku_id>\d+)/$',GoodsDetailView.as_view()),
    # 统计分类商品访问量
    url(r'^visit/(?P<category_id>\d+)/$',GoodsVisitView.as_view()),
    # 分类商品评论展示        /comments/'+ this.sku_id +'/
    url(r'^comments/(?P<sku_id>\d+)/$',GoodsCommentsView.as_view()),
    ]

meiduo/meiduo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('users.urls')),   #用户路由 总路由和总设置中的注册应用使用相同的导包路径
    url(r'^',include('verifications.urls')),   #图形验证码和短信验证码路由
    url(r'^',include('contents.urls')),   #首页路由
    url(r'^',include('oauth.urls')),   #qq登录路由
    url(r'^',include('areas.urls')),   #省市区三级联动路由
    url(r'^',include('goods.urls')),   #商品展示路由
    url(r'^',include('carts.urls')),   #购物车展示路由
    url(r'^',include('orders.urls')),   #订单路由
    url(r'^',include('payment.urls')),   #支付路由
    url(r'^',include('weibo.urls')),   #微博登录路由
    url(r'meiduo_admin/',include('meiduo_admin.urls')),  #后台管理登录
]

meiduo/meiduo/apps/carts/models.py
from django.db import models

# Create your models here.

meiduo/meiduo/apps/goods/models.py
from django.db import models
from meiduo.utils.models import BaseModel
# Create your models here.
class GoodsCategory(BaseModel):
    """商品类别"""
    name = models.CharField(max_length=10, verbose_name='名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    group = models.ForeignKey(GoodsChannelGroup, verbose_name='频道组名')
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='顶级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='名称')
    logo = models.ImageField(verbose_name='Logo图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='商品')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)


class GoodsVisitCount(BaseModel):
    category = models.ForeignKey(GoodsCategory,on_delete=models.CASCADE,verbose_name='商品分类')
    count = models.IntegerField(default=0,verbose_name='访问量')
    date = models.DateField(auto_now_add=True,verbose_name='统计日期')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name

meiduo/meiduo/apps/areas/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse,HttpResponseForbidden
from django.core.cache import cache
from .models import Area
from meiduo.utils.response_code import RETCODE

class AreasViews(View):
    """获取省市区信息"""
    def get(self,request):
        #url = this.host + '/areas/?area_id=' + this.form_address.city_id;
        #1.接收数据
        id = request.GET.get("area_id")
        #2.判断是否有查询参数，没有查询参数说明是获取省份数据，有查询参数是查询市区信息
        #采用mysql磁盘型数据库存储数据，将来查找的次数过多会大大降低mysql的性能
        #对于获取省份数据而言，每个用户都要获取，可以在第一次获取时将其加载到redis内存中，这样就不用每次都操作mysql数据库了
        # 3.业务逻辑处理
        if id is None:
            #获取省份数据
            #3.0 先判断redis中有没有省份数据，如果有直接从redis读取，如果没有就从mysql读取，读完后存到redis中
            #借助django封装的方法可以解决
            province_list = cache.get('province_list')
            #如果能从redis中获取数据，则直接响应
            if province_list is None:
            #3.1获取所有的省级信息

                province_qs = Area.objects.filter(parent=None)
                #3.2 获得的是queryset类型，不能直接传给json数据，需要将其包装成字典或者列表
                province_list = []
                for province in province_qs:
                    province_dict = {'id':province.id,'name':province.name}
                    province_list.append(province_dict)
                #将获取到的数据存入redis
                cache.set("province_list",province_list,3600)
            # 4.响应Json数据
            return JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK','province_list':province_list})

        else:
            #查询市区信息 id = request.GET.get("area_id")
            #1.根据获取的省级id信息，查询下面所有的市
            #市区信息也可以用redis存储
            #先查看redis中有没有，没有就用mysql查，有就直接用redis缓存的数据
            sub_data = cache.get("sub_data_%s" %id)
            if sub_data is None:
                try:
                    area = Area.objects.get(id=id)  #获取模型对象
                    city_qs = area.subs.all()  #得到qs集合
                # "sub_data" = {
                #     "id"=id,
                #     "name"=name,
                #     "subs"=[
                #         {'id':id,'name':name}
                #     ]
                # }
                except Area.DoesNotExist:
                    return HttpResponseForbidden("缺少id值")

                # 2.将area和city_qs数据以json形式响应
                subs = []
                for city in city_qs:
                    subs_dict = {'id': city.id, 'name': city.name}
                    subs.append(subs_dict)
                sub_data = {'id': area.id, 'name': area.name, "subs": subs}
                cache.set("sub_data_%s" %id,sub_data,3600)
            return JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'sub_data': sub_data})

meiduo/meiduo/apps/goods/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseForbidden,JsonResponse
from django.core.paginator import Paginator
from django.utils import timezone
from .models import GoodsCategory,SKU,GoodsVisitCount
from .utils import breadcrumb
from contents.utils import get_category
from meiduo.utils.response_code import RETCODE
from meiduo.utils.views import LoginRequireView
from orders.models import OrderInfo
# Create your views here.

class ListView(View):
    """商品列表页面展示"""
    def get(self,request,category_id,page_num):
        #1.获取数据
        #category_id 代表商品类别表中的三级标题id， page_num代表查询的页数
        #sort=price  获取商品的展示方式，如果没有，默认为default
        sort = request.GET.get('sort','default')
        #2.校验
        #防止恶意访问
        try:
            cat3 = GoodsCategory.objects.get(id=category_id)  #获取对应的三级标题对象
        except GoodsCategory.DoesNotExist:
            return HttpResponseForbidden("id错误")
        #3.业务逻辑处理
        #3.0按哪种方式排序
        if sort == 'price':
            sort_page = '-price'
        elif sort == 'hot':
            sort_page = '-sales'
        else:
            sort = 'default'
            sort_page = 'create_time'
        #3.1获取商品三级分类展示
        categories = get_category()
        #3.2面包屑导航


        page = 5

        #3.3 获取三级分类下所有的SKU商品
        sku_qs = cat3.sku_set.filter(is_launched=True).order_by(sort_page)
        # 3.4  获取总页数
        # total_page = sku_qs.count() // page + 1 if sku_qs.count() % page else 0
        # 3.5 获取指定页的商品
        page_num = int(page_num)
        # sku_index = sku_qs[(page_num-1)*page:(page_num-1)*page+page]
        #3.6 django已经帮我们封装了分页的方法
        paginator = Paginator(sku_qs,page)
        try:
            sku_index = paginator.page(page_num)  #获取指定页的商品
            total_page = paginator.num_pages   #获取总页数
        except:
            return HttpResponseForbidden("查不到指定页")

        #4.响应
        context = {
            'categories':categories,
            'breadcrumb':breadcrumb(cat3),
            'category': cat3,
            'sort':sort,
            'page_skus':sku_index,  # 指定页的sku数据
            'page_num':page_num,   #当前显示的是第几页
            'total_page':total_page,  #总页数
        }
        return render(request,'list.html',context)

class HotGoodsView(View):
    """热销商品展示"""
    def get(self,request,category_id):
        #1.接收数据
        #2.校验
        #检验该三级标题是否存在
        try:
            cat3 = GoodsCategory.objects.get(id=category_id)
        except GoodsCategory.DoesNotExist:
            return HttpResponseForbidden('id不存在')
        #3.业务逻辑处理
        #3.1查询该三级标题下所有的商品，按照销量排序
        sku_qs = cat3.sku_set.order_by('-sales')
        #3.2截取前两个作为展示
        sku_qs_limit = sku_qs[0:2]
        #4.响应json数据，hot_skus
        #4.1包装成json数据
        hot_skus_list = []
        for sku in sku_qs_limit:
            hot_skus_dict = {
                'id':sku.id,
                'name':sku.name,
                'default_image_url':sku.default_image.url,
                'price':sku.price,
            }
            hot_skus_list.append(hot_skus_dict)
        return JsonResponse({'code':RETCODE.OK,'errmgs':'ok','hot_skus':hot_skus_list})

class GoodsDetailView(View):
    """商品详情页展示"""
    def get(self,request,sku_id):
        #1.获取数据
        #2.校验
        try:
            sku = SKU.objects.get(id=sku_id)
        except SKU.DoesNotExist:
            return HttpResponseForbidden('商品不存在')
        #3.业务逻辑处理
        cat3 = sku.category  #获取对应的三级标题
        spu = sku.spu  #获取对应的SPU
        """1.准备当前商品的规格选项列表 [8, 11]"""
        # 获取出当前正显示的sku商品的规格选项id列表
        current_sku_spec_qs = sku.specs.order_by('spec_id')
        current_sku_option_ids = []  # [8, 11]
        for current_sku_spec in current_sku_spec_qs:
            current_sku_option_ids.append(current_sku_spec.option_id)

        """2.构造规格选择仓库
        {(8, 11): 3, (8, 12): 4, (9, 11): 5, (9, 12): 6, (10, 11): 7, (10, 12): 8}
        """
        # 构造规格选择仓库
        temp_sku_qs = spu.sku_set.all()  # 获取当前spu下的所有sku
        # 选项仓库大字典
        spec_sku_map = {}  # {(8, 11): 3, (8, 12): 4, (9, 11): 5, (9, 12): 6, (10, 11): 7, (10, 12): 8}
        for temp_sku in temp_sku_qs:
            # 查询每一个sku的规格数据
            temp_spec_qs = temp_sku.specs.order_by('spec_id')
            temp_sku_option_ids = []  # 用来包装每个sku的选项值
            for temp_spec in temp_spec_qs:
                temp_sku_option_ids.append(temp_spec.option_id)
            spec_sku_map[tuple(temp_sku_option_ids)] = temp_sku.id

        """3.组合 并找到sku_id 绑定"""
        spu_spec_qs = spu.specs.order_by('id')  # 获取当前spu中的所有规格

        for index, spec in enumerate(spu_spec_qs):  # 遍历当前所有的规格
            spec_option_qs = spec.options.all()  # 获取当前规格中的所有选项
            temp_option_ids = current_sku_option_ids[:]  # 复制一个新的当前显示商品的规格选项列表
            for option in spec_option_qs:  # 遍历当前规格下的所有选项
                temp_option_ids[index] = option.id  # [8, 12]
                option.sku_id = spec_sku_map.get(tuple(temp_option_ids))  # 给每个选项对象绑定下他sku_id属性

            spec.spec_options = spec_option_qs  # 把规格下的所有选项绑定到规格对象的spec_options属性上

        #4.渲染页面
        context = {
            'categories':get_category(),
            'breadcrumb':breadcrumb(cat3),
            'sku':sku,
            'category':cat3,
            'spu':spu,
            'spec_qs':spu_spec_qs,  # 当前商品的所有规格数据
        }
        return render(request,'detail.html',context)

class GoodsVisitView(View):
    """商品三级类别统计访问量"""
    def post(self,request,category_id):
        #1.接收数据  正则匹配出的数据返回都是字符串
        #2.校验数据
        #查看该三级id是否存在
        try:
            cat3 = GoodsCategory.objects.get(id=category_id)
        except GoodsCategory.DoesNotExist:
            return HttpResponseForbidden('id不存在')
        #3.业务逻辑处理
        #需要单独建立商品访问量的数据库表，查看数据,如果能查到说明今天已有访问，未查到说明没有访问过
        today = timezone.now()
        try:
            # 3.1如果该商品类当天已经被访问过，则修改该数据的count+1
            goods_visit = cat3.goodsvisitcount_set.get(date=today)

        except:
            # 3.1如果该商品类当天还未被访问，则新增一条数据

            goods_visit = GoodsVisitCount()
            goods_visit.category_id = category_id
        goods_visit.count += 1
        goods_visit.save()
        #4.响应json
        return JsonResponse({'code':RETCODE.OK,'errmsg':'OK'})

class GoodsCommentsView(View):
    """商品类评论展示"""
    def get(self,request,sku_id):
        #1.获取数据
        #2.校验数据
        try:
            sku = SKU.objects.get(id=sku_id)
        except SKU.DoesNotExist:
            return HttpResponseForbidden('查无此商品')
        #3.业务逻辑处理
        comment_list = []
        order_goods_qs = sku.ordergoods_set.filter(is_commented=True)
        for order_goods in order_goods_qs:
            order = order_goods.order
            origin_username = order.user.username
            username = origin_username[:1]+'****'+origin_username[-3:-1]
            comment_list.append({
                'username':username,
                'content':order_goods.comment,
            })
        #4.响应json
        return JsonResponse({'code':RETCODE.OK,'errmsg':'OK','comment_list':comment_list})

meiduo/meiduo/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-登录</title>
    <link rel="stylesheet" type="text/css" href="{{ static('css/reset.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ static('css/main.css') }}">
    <script type="text/javascript" src="{{ static('js/host.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/vue-2.5.16.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/axios-0.18.0.min.js') }}"></script>
</head>
<body>
<div class="login_top clearfix">
    <a href="/" class="login_logo"><img src="{{ static('images/logo02.png') }}"></a>
</div>

<div class="login_form_bg" id="app">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">商品美 · 种类多 · 欢迎光临</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <a href="javascript:;" class="cur">账户登录</a>
            </div>
            <div class="form_con">
                <div class="form_input cur">
                    <form method="post" id="login-form" @submit="on_submit">

                        
                        {{ csrf_input }}

                        <input type="text" v-model="username" @blur="check_username" name="username" class="name_input"
                               placeholder="请输入用户名或手机号">
                        <div v-show="error_username" class="user_error" v-cloak>请输入正确的用户名或手机号</div>
                        <input type="password" v-model="password" @blur="check_pwd" name="password" class="pass_input"
                               placeholder="请输入密码">
                        <div v-show="error_pwd" class="pwd_error" v-cloak>密码最少8位，最长20位</div>
                        {% if account_errmsg %}
                            <div class="pwd_error">{{ account_errmsg }}</div>
                        {% endif %}
                        <div class="more_input clearfix">
                            <input type="checkbox" v-model="remembered" name="remembered">
                            <label>记住登录</label>
                        </div>
                        <input type="submit" value="登 录" class="input_submit">
                    </form>
                </div>
            </div>
            <div class="third_party">
                <a @click="qq_login" class="qq_login">QQ</a>
                <a @click="weibo_login" class="weixin_login">微博</a>
{#                <a href="#" class="weixin_login"></a>#}
                <a href="/register/" class="register_btn">立即注册</a>
            </div>

        </div>
    </div>
</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
<script>

</script>
<script type="text/javascript" src="{{ static('js/login.js') }}"></script>
<script type="text/javascript" src="{{ static('js/common.js') }}"></script>
</body>
</html>

meiduo/meiduo/templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-我的订单</title>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.pagination.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
    <script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
</head>
<body>
<div id="app" v-cloak>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到美多商城!</div>
            <div class="fr">
                <div class="login_btn fl" v-if="username">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="/logout/" class="quit">退出</a>
                </div>
                <div class="login_btn fl" v-else>
                    <a href="/login/">登录</a>
                    <span>|</span>
                    <a href="/register/">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="/info/">用户中心</a>
                    <span>|</span>
                    <a href="/carts/">我的购物车</a>
                    <span>|</span>
                    <a href="/orders/info/1/">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
    </div>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/info/">· 个人信息</a></li>
                <li><a href="/orders/info/1/" class="active">· 全部订单</a></li>
                <li><a href="/addresses/">· 收货地址</a></li>
                <li><a href="/password/">· 修改密码</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in page_orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time.strftime('%Y-%m-%d %H:%M:%S') }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                </ul>
                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for sku in order.sku_list %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image_url}}"></li>
                                    <li class="col02"><span>{{ sku.name }}</span><em>{{ sku.price }}元</em></li>
                                    <li class="col03">{{ sku.count }}</li>
                                    <li class="col04">{{ sku.amount }}元</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_amount }}元<br>含运费：{{ order.freight }}元</td>
                        <td width="15%">{{ order.pay_method_name }}</td>
                        <td width="15%">
                            <a @click="oper_btn_click('{{ order.order_id }}', {{ order.status }})"
                               class="oper_btn">{{ order.status_name }}</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
            <div class="pagenation">
                <div id="pagination" class="page"></div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
<script type="text/javascript" src="/static/js/jquery.pagination.min.js"></script>
<script type="text/javascript" src="/static/js/common.js"></script>
<script type="text/javascript" src="/static/js/base.js"></script>
<script type="text/javascript" src="/static/js/user_center_order.js"></script>
<script>
    $(function () {
        $('#pagination').pagination({
            currentPage: {{ page_num }},
            totalPage: {{ total_page }},
            callback: function (current) {
                location.href = '/orders/info/' + current + '/';
            }
        })
    });
</script>

</body>
</html>